# Generated by Django 4.0.4 on 2022-06-22 13:49

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', verbose_name='About page text')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, size=[1500, 1500], upload_to='info')),
            ],
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', verbose_name='Contacts page text')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, size=[1500, 1500], upload_to='info')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', verbose_name='Discounts page text')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, size=[1500, 1500], upload_to='info')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='topic')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='name')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, size=[1500, 1500], upload_to='info')),
                ('video', models.CharField(blank=True, default='', max_length=1000, verbose_name='video')),
                ('info', models.TextField(blank=True, default='', verbose_name='text')),
                ('title_tag', models.CharField(blank=True, default='', max_length=70, verbose_name='title tag')),
                ('description_tag', models.CharField(blank=True, default='', max_length=280, verbose_name='description tag')),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Infos',
            },
        ),
        migrations.CreateModel(
            name='RefundPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', verbose_name='Refund page text')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, size=[1500, 1500], upload_to='info')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', verbose_name='Shipping page text')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, size=[1500, 1500], upload_to='info')),
            ],
        ),
        migrations.CreateModel(
            name='SizingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', verbose_name='Sizing page text')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, size=[1500, 1500], upload_to='info')),
            ],
        ),
    ]
