# Generated by Django 4.0.4 on 2022-07-15 07:46

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='image',
            new_name='image_1',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='text',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image_1_en',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image_1_ru',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image_1_uk',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image_2_en',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image_2_ru',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image_2_uk',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='text_1',
            field=models.TextField(blank=True, default='', verbose_name='About page text (frst prt'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='text_1_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='About page text (frst prt'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='text_1_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='About page text (frst prt'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='text_1_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='About page text (frst prt'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='text_2',
            field=models.TextField(blank=True, default='', verbose_name='About page text (scnd prt'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='text_2_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='About page text (scnd prt'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='text_2_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='About page text (scnd prt'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='text_2_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='About page text (scnd prt'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='image_en',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='image_ru',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='image_uk',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='text_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Contacts page text'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='text_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Contacts page text'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='text_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Contacts page text'),
        ),
        migrations.AddField(
            model_name='discountspage',
            name='image_en',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='discountspage',
            name='image_ru',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='discountspage',
            name='image_uk',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='discountspage',
            name='text_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Discounts page text'),
        ),
        migrations.AddField(
            model_name='discountspage',
            name='text_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Discounts page text'),
        ),
        migrations.AddField(
            model_name='discountspage',
            name='text_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Discounts page text'),
        ),
        migrations.AddField(
            model_name='refundpage',
            name='image_en',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='refundpage',
            name='image_ru',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='refundpage',
            name='image_uk',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='refundpage',
            name='text_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Refund page text'),
        ),
        migrations.AddField(
            model_name='refundpage',
            name='text_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Refund page text'),
        ),
        migrations.AddField(
            model_name='refundpage',
            name='text_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Refund page text'),
        ),
        migrations.AddField(
            model_name='shippingpage',
            name='image_en',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='shippingpage',
            name='image_ru',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='shippingpage',
            name='image_uk',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='shippingpage',
            name='text_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Shipping page text'),
        ),
        migrations.AddField(
            model_name='shippingpage',
            name='text_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Shipping page text'),
        ),
        migrations.AddField(
            model_name='shippingpage',
            name='text_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Shipping page text'),
        ),
        migrations.AddField(
            model_name='sizingpage',
            name='image_en',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='sizingpage',
            name='image_ru',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='sizingpage',
            name='image_uk',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='sizingpage',
            name='text_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Sizing page text'),
        ),
        migrations.AddField(
            model_name='sizingpage',
            name='text_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Sizing page text'),
        ),
        migrations.AddField(
            model_name='sizingpage',
            name='text_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Sizing page text'),
        ),
    ]
