# Generated by Django 4.0.4 on 2022-07-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_delete_info_rename_image_aboutpage_image_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', verbose_name='Refund page text')),
                ('text_uk', models.TextField(blank=True, default='', null=True, verbose_name='Refund page text')),
                ('text_ru', models.TextField(blank=True, default='', null=True, verbose_name='Refund page text')),
                ('text_en', models.TextField(blank=True, default='', null=True, verbose_name='Refund page text')),
            ],
        ),
    ]
