# Generated by Django 4.0.4 on 2022-07-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_termspage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termspage',
            old_name='text',
            new_name='privacy',
        ),
        migrations.RenameField(
            model_name='termspage',
            old_name='text_en',
            new_name='privacy_en',
        ),
        migrations.RenameField(
            model_name='termspage',
            old_name='text_ru',
            new_name='privacy_ru',
        ),
        migrations.RenameField(
            model_name='termspage',
            old_name='text_uk',
            new_name='privacy_uk',
        ),
        migrations.AddField(
            model_name='termspage',
            name='terms',
            field=models.TextField(blank=True, default='', verbose_name='Refund page text'),
        ),
        migrations.AddField(
            model_name='termspage',
            name='terms_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Refund page text'),
        ),
        migrations.AddField(
            model_name='termspage',
            name='terms_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Refund page text'),
        ),
        migrations.AddField(
            model_name='termspage',
            name='terms_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Refund page text'),
        ),
    ]
