# Generated by Django 4.0.4 on 2022-07-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_rename_text_termspage_privacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termspage',
            name='privacy',
            field=models.TextField(blank=True, default='', verbose_name='Privacy policy'),
        ),
        migrations.AlterField(
            model_name='termspage',
            name='privacy_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Privacy policy'),
        ),
        migrations.AlterField(
            model_name='termspage',
            name='privacy_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Privacy policy'),
        ),
        migrations.AlterField(
            model_name='termspage',
            name='privacy_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Privacy policy'),
        ),
        migrations.AlterField(
            model_name='termspage',
            name='terms',
            field=models.TextField(blank=True, default='', verbose_name='Terms of use'),
        ),
        migrations.AlterField(
            model_name='termspage',
            name='terms_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Terms of use'),
        ),
        migrations.AlterField(
            model_name='termspage',
            name='terms_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Terms of use'),
        ),
        migrations.AlterField(
            model_name='termspage',
            name='terms_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Terms of use'),
        ),
    ]
