# Generated by Django 4.0.4 on 2022-08-05 10:03

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_aboutpage_options_alter_contactspage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, verbose_name='tag')),
                ('text_1', models.TextField(blank=True, default='', verbose_name='frst prt')),
                ('image_1', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, size=[1500, 1500], upload_to='info')),
                ('text_2', models.TextField(blank=True, default='', verbose_name='scnd prt')),
                ('image_2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, size=[1500, 1500], upload_to='info')),
            ],
            options={
                'verbose_name': 'About page',
                'verbose_name_plural': 'About page',
            },
        ),
    ]
