# Generated by Django 4.0.4 on 2022-08-06 08:20

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_infopages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infopages',
            options={'verbose_name': 'Info pages', 'verbose_name_plural': 'Info pages'},
        ),
        migrations.AddField(
            model_name='infopages',
            name='image_1_en',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='infopages',
            name='image_1_ru',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='infopages',
            name='image_1_uk',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='infopages',
            name='image_2_en',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='infopages',
            name='image_2_ru',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='infopages',
            name='image_2_uk',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AddField(
            model_name='infopages',
            name='tag_en',
            field=models.CharField(max_length=20, null=True, verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='infopages',
            name='tag_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='infopages',
            name='tag_uk',
            field=models.CharField(max_length=20, null=True, verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='infopages',
            name='text_1_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='frst prt'),
        ),
        migrations.AddField(
            model_name='infopages',
            name='text_1_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='frst prt'),
        ),
        migrations.AddField(
            model_name='infopages',
            name='text_1_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='frst prt'),
        ),
        migrations.AddField(
            model_name='infopages',
            name='text_2_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='scnd prt'),
        ),
        migrations.AddField(
            model_name='infopages',
            name='text_2_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='scnd prt'),
        ),
        migrations.AddField(
            model_name='infopages',
            name='text_2_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='scnd prt'),
        ),
    ]
