# Generated by Django 4.0.4 on 2022-06-22 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('showcase', '0007_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=32, verbose_name='name')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ('added',),
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='first name')),
                ('last_name', models.CharField(max_length=70, verbose_name='last name')),
                ('phone', models.CharField(db_index=True, max_length=32, verbose_name='phone')),
                ('comment', models.TextField(blank=True, default='', verbose_name='comment')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('lang_code', models.CharField(blank=True, default='ru', max_length=2, verbose_name='lang code')),
                ('delivered', models.BooleanField(default=False, verbose_name='delivered')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('date_of_delivery', models.DateField(blank=True, null=True, verbose_name='date_of_delivery')),
                ('delivery_method', models.IntegerField(choices=[(0, 'World wide'), (1, 'NovaPoshta to branch'), (2, 'NovaPoshta to the door'), (3, 'Ukrposhta to the branch'), (4, 'Ukrposhta to the door'), (5, 'Justin to the branch')], default=0, verbose_name='delivery_method')),
                ('payment_method', models.IntegerField(choices=[(0, 'Visa / Mastercard'), (1, 'ApplePay'), (2, 'GooglePay'), (3, 'PayPal'), (4, 'Pay by card'), (5, 'Cash on delivery')], default=0, verbose_name='payment_method')),
                ('liqpay_wait_accept', models.BooleanField(default=False, verbose_name='LiqPay wait accept')),
                ('wfp_status', models.CharField(blank=True, default='', max_length=512, verbose_name='WFP status')),
                ('ttn', models.IntegerField(default=0, verbose_name='TTN')),
                ('packed', models.BooleanField(default=False, verbose_name='Packed')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
            ],
            options={
                'verbose_name': 'Orders',
                'verbose_name_plural': 'Orders',
                'ordering': ('-added',),
            },
        ),
        migrations.CreateModel(
            name='PaymentRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(verbose_name='data')),
                ('sign', models.TextField(verbose_name='sign')),
                ('data_decoded', models.TextField(blank=True, default='', verbose_name='data decoded')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('comment', models.CharField(max_length=512, verbose_name='comment')),
                ('token', models.CharField(blank=True, max_length=512, verbose_name='liqpay token')),
                ('sender_phone', models.CharField(blank=True, max_length=64, verbose_name='liqpay sender phone')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='price')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.balance')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
                'ordering': ('added',),
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.items')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.sizes')),
            ],
        ),
    ]
