# Generated by Django 4.0.4 on 2022-06-14 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='amount')),
            ],
            options={
                'verbose_name': 'Amount of items',
                'verbose_name_plural': 'Amount of items',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='name')),
                ('details', models.TextField(blank=True, verbose_name='details')),
                ('title_tag', models.CharField(blank=True, default='', max_length=70, verbose_name='title tag')),
                ('description_tag', models.CharField(blank=True, default='', max_length=280, verbose_name='description tag')),
                ('sequence', models.PositiveSmallIntegerField(default=0, verbose_name='sequence')),
                ('showcase_displayed', models.BooleanField(default=True, verbose_name='showcase_displayed')),
            ],
            options={
                'verbose_name': 'Categories of items',
                'verbose_name_plural': 'Categories of items',
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, size=[2500, 2500], upload_to='photos/%Y/%m/%d')),
                ('image_small', django_resized.forms.ResizedImageField(crop=['middle', 'center'], editable=False, force_format=None, keep_meta=True, quality=-1, size=[300, 300], upload_to='small_photos/%Y/%m/%d')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('details', models.TextField(blank=True, default='', verbose_name='details')),
                ('details_rozetka', models.TextField(blank=True, default='', verbose_name='details rozetka')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='price')),
                ('price_description', models.CharField(default='Grn.', max_length=250, verbose_name='price_description')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('views_today', models.PositiveIntegerField(default=0, verbose_name='views today')),
                ('views_month', models.CharField(default=0, max_length=512, verbose_name='views month')),
                ('showcase_displayed', models.BooleanField(default=True, verbose_name='showcase_displayed')),
                ('showcase_avail', models.BooleanField(default=False, verbose_name='showcase_avail')),
                ('showcase_new', models.BooleanField(default=True, verbose_name='showcase_new')),
                ('title_tag', models.CharField(blank=True, default='', max_length=70, verbose_name='title tag')),
                ('description_tag', models.CharField(blank=True, default='', max_length=280, verbose_name='description tag')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.categories')),
            ],
            options={
                'verbose_name': 'items',
                'verbose_name_plural': 'items',
                'ordering': ('-views',),
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Unconditional'), (1, 'Order items count'), (2, 'Conditional')], verbose_name='type')),
                ('items_count', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='items count')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, size=[2500, 2500], upload_to='photos/%Y/%m/%d')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='discount')),
                ('action_begin', models.DateField(verbose_name='action_begin')),
                ('action_end', models.DateField(verbose_name='action_end')),
                ('categories', models.ManyToManyField(blank=True, to='showcase.categories')),
            ],
            options={
                'verbose_name': 'stocks',
                'verbose_name_plural': 'stocks',
                'ordering': ('action_begin',),
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('sequence', models.PositiveSmallIntegerField(default=0, verbose_name='sequence')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.categories')),
            ],
            options={
                'verbose_name': 'Sizes of items',
                'verbose_name_plural': 'Sizes of items',
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, size=[2500, 2500], upload_to='photos/%Y/%m/%d')),
                ('image_small', django_resized.forms.ResizedImageField(crop=['middle', 'center'], editable=False, force_format=None, keep_meta=True, quality=-1, size=[300, 300], upload_to='small_photos/%Y/%m/%d')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.items')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ('added',),
            },
        ),
        migrations.CreateModel(
            name='BalanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.IntegerField(verbose_name='old value')),
                ('new_value', models.IntegerField(verbose_name='new value')),
                ('arrival', models.BooleanField(default=False, verbose_name='arrival')),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Balance log',
                'verbose_name_plural': 'Balance logs',
                'ordering': ('-change_time',),
            },
        ),
        migrations.AddField(
            model_name='balance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.items'),
        ),
        migrations.AddField(
            model_name='balance',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.sizes'),
        ),
    ]
