# Generated by Django 4.0.4 on 2022-06-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description_tag_en',
            field=models.CharField(blank=True, default='', max_length=280, null=True, verbose_name='description tag'),
        ),
        migrations.AddField(
            model_name='categories',
            name='description_tag_ru',
            field=models.CharField(blank=True, default='', max_length=280, null=True, verbose_name='description tag'),
        ),
        migrations.AddField(
            model_name='categories',
            name='description_tag_uk',
            field=models.CharField(blank=True, default='', max_length=280, null=True, verbose_name='description tag'),
        ),
        migrations.AddField(
            model_name='categories',
            name='details_en',
            field=models.TextField(blank=True, null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='categories',
            name='details_ru',
            field=models.TextField(blank=True, null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='categories',
            name='details_uk',
            field=models.TextField(blank=True, null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_en',
            field=models.CharField(max_length=70, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_ru',
            field=models.CharField(max_length=70, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_uk',
            field=models.CharField(max_length=70, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='categories',
            name='title_tag_en',
            field=models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='title tag'),
        ),
        migrations.AddField(
            model_name='categories',
            name='title_tag_ru',
            field=models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='title tag'),
        ),
        migrations.AddField(
            model_name='categories',
            name='title_tag_uk',
            field=models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='title tag'),
        ),
        migrations.AddField(
            model_name='items',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='items',
            name='description_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='items',
            name='description_tag_en',
            field=models.CharField(blank=True, default='', max_length=280, null=True, verbose_name='description tag'),
        ),
        migrations.AddField(
            model_name='items',
            name='description_tag_ru',
            field=models.CharField(blank=True, default='', max_length=280, null=True, verbose_name='description tag'),
        ),
        migrations.AddField(
            model_name='items',
            name='description_tag_uk',
            field=models.CharField(blank=True, default='', max_length=280, null=True, verbose_name='description tag'),
        ),
        migrations.AddField(
            model_name='items',
            name='description_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='items',
            name='details_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='items',
            name='details_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='items',
            name='details_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='items',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='items',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='items',
            name='name_uk',
            field=models.CharField(max_length=250, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='items',
            name='price_description_en',
            field=models.CharField(default='Grn.', max_length=250, null=True, verbose_name='price_description'),
        ),
        migrations.AddField(
            model_name='items',
            name='price_description_ru',
            field=models.CharField(default='Grn.', max_length=250, null=True, verbose_name='price_description'),
        ),
        migrations.AddField(
            model_name='items',
            name='price_description_uk',
            field=models.CharField(default='Grn.', max_length=250, null=True, verbose_name='price_description'),
        ),
        migrations.AddField(
            model_name='items',
            name='title_tag_en',
            field=models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='title tag'),
        ),
        migrations.AddField(
            model_name='items',
            name='title_tag_ru',
            field=models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='title tag'),
        ),
        migrations.AddField(
            model_name='items',
            name='title_tag_uk',
            field=models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='title tag'),
        ),
        migrations.AddField(
            model_name='sizes',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='sizes',
            name='description_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='sizes',
            name='description_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='sizes',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='sizes',
            name='name_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='sizes',
            name='name_uk',
            field=models.CharField(max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='description_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='description_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='name_uk',
            field=models.CharField(max_length=250, null=True, verbose_name='name'),
        ),
    ]
