# Generated by Django 4.0.4 on 2022-06-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_categories_description_tag_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ('id',), 'verbose_name': 'Amount', 'verbose_name_plural': 'Amount'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('sequence',), 'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='sizes',
            options={'ordering': ('sequence',), 'verbose_name': 'Sizes', 'verbose_name_plural': 'Sizes'},
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
    ]
