# Generated by Django 4.0.4 on 2022-06-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_remove_items_details_rozetka_alter_items_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='showcase_avail',
        ),
    ]
