# Generated by Django 4.0.4 on 2022-06-15 18:44

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_remove_items_showcase_avail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_showcase', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, size=[2000, 300], upload_to='photos/%Y/%m/%d')),
                ('image_category', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, size=[2000, 300], upload_to='photos/%Y/%m/%d')),
            ],
        ),
    ]
