# Generated by Django 4.0.4 on 2022-06-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollar_rate', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='dollar rate')),
                ('euro_rate', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='euro rate')),
                ('price_description', models.CharField(default='Grn.', max_length=250, verbose_name='price_description')),
                ('price_description_usd', models.CharField(default='Usd.', max_length=250, verbose_name='price_description')),
                ('price_description_eur', models.CharField(default='Eur.', max_length=250, verbose_name='price_description')),
            ],
            options={
                'verbose_name': 'Config',
                'verbose_name_plural': 'Config',
                'ordering': ('dollar_rate',),
            },
        ),
    ]
