# Generated by Django 4.0.4 on 2022-07-15 11:57

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0008_config_media_config_merchant_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_category_en',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[2000, 300], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_category_ru',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[2000, 300], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_category_uk',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[2000, 300], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_showcase_en',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[2000, 300], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_showcase_ru',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[2000, 300], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_showcase_uk',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[2000, 300], upload_to='photos/%Y/%m/%d'),
        ),
    ]
