# Generated by Django 4.0.4 on 2022-07-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0009_banner_image_category_en_banner_image_category_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banners', 'verbose_name_plural': 'Banners page'},
        ),
        migrations.AlterField(
            model_name='config',
            name='price_description',
            field=models.CharField(default='Грн', max_length=250, verbose_name='price_description'),
        ),
        migrations.AlterField(
            model_name='config',
            name='price_description_en',
            field=models.CharField(default='Грн', max_length=250, null=True, verbose_name='price_description'),
        ),
        migrations.AlterField(
            model_name='config',
            name='price_description_ru',
            field=models.CharField(default='Грн', max_length=250, null=True, verbose_name='price_description'),
        ),
        migrations.AlterField(
            model_name='config',
            name='price_description_uk',
            field=models.CharField(default='Грн', max_length=250, null=True, verbose_name='price_description'),
        ),
    ]
